--- 
abstract: UserAgent that looks up passwords on Mac OS X keychain
author: 
  - Tatsuhiko Miyagawa <miyagawa@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: LWP-UserAgent-Keychain
no_index: 
  directory: 
    - inc
    - t
requires: 
  LWP::UserAgent: 0
  Mac::Glue: 0
  perl: 5.8.1
version: 0.01
